import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';
import fs from 'node:fs';

import { toSafeName } from '#/util/JString.js';

import { verifyOwnerHeader } from './ownerAssertion.js';

const SECRET = 'x'.repeat(32);
const NOW = 1_800_000_000_000;

// Mirrors server/src/auth/ownerAssertion.ts exactly; if these two ever disagree, logins break.
function entry(uid: string, character: string, exp: number, secret = SECRET): string {
    const sig = createHmac('sha256', secret).update(`cs1|${uid}|${character}|${exp}`).digest('base64url');
    return `${uid}.${character}.${exp}.${sig}`;
}

test('accepts the entry whose character matches the decrypted login name', () => {
    const header = `${entry('u1', 'alice', NOW + 1000)}~${entry('u1', 'bob', NOW + 1000)}`;
    assert.deepEqual(verifyOwnerHeader(header, 'bob', SECRET, NOW), { uid: 'u1', character: 'bob', exp: NOW + 1000 });
});

test('refuses a name with no entry, a forged signature, a wrong secret and an expired entry', () => {
    const header = entry('u1', 'alice', NOW + 1000);
    assert.equal(verifyOwnerHeader(header, 'mallory', SECRET, NOW), null);
    assert.equal(verifyOwnerHeader(`${header}x`, 'alice', SECRET, NOW), null);
    assert.equal(verifyOwnerHeader(header, 'alice', 'y'.repeat(32), NOW), null);
    assert.equal(verifyOwnerHeader(entry('u1', 'alice', NOW - 1), 'alice', SECRET, NOW), null);
});

test('refuses to authorise anything when no secret is configured', () => {
    assert.equal(verifyOwnerHeader(entry('u1', 'alice', NOW + 1000), 'alice', '', NOW), null);
});

test('survives junk headers without throwing', () => {
    for (const bad of [null, '', '~~~', 'a.b', 'a.b.c.d.e', `${'a'.repeat(5000)}`]) {
        assert.equal(verifyOwnerHeader(bad, 'alice', SECRET, NOW), null);
    }
});

test('an entry for the right name but a different uid still binds to that uid', () => {
    // Two accounts cannot both own one name (gameNames/{name} is a unique index on the front
    // server), so whichever uid signed for this name is the owner of the bank it opens.
    const parsed = verifyOwnerHeader(entry('u2', 'alice', NOW + 1000), 'alice', SECRET, NOW);
    assert.equal(parsed?.uid, 'u2');
});

// The engine never compares the raw login name: PlayerLoading.load passes
// fromBase37(toBase37(name)), i.e. toSafeName. toBase37 folds A-Z onto the same values as a-z
// and fromBase37 emits from a lowercase lookup table, so a mixed-case login collapses onto the
// lowercase gameName the front server signed. If that ever stopped holding, every login from a
// player who typed their name with capitals would be refused, so it is pinned here.
test('a mixed-case login name matches its lowercase entry, because toSafeName lowercases', () => {
    assert.equal(toSafeName('AlIcE'), 'alice');
    assert.equal(toSafeName('Alice Smith'), 'alice_smith');

    const header = entry('u1', 'alice', NOW + 1000);
    assert.deepEqual(verifyOwnerHeader(header, toSafeName('AlIcE'), SECRET, NOW), { uid: 'u1', character: 'alice', exp: NOW + 1000 });
    // ...and the raw, un-normalised name is not what the entry is keyed on.
    assert.equal(verifyOwnerHeader(header, 'AlIcE', SECRET, NOW), null);
});

// --- The shared vector file (the drift alarm) --------------------------------
// ownerAssertion.vectors.json is generated by the FRONT SERVER's signOwnerAssertion and is
// read by this suite AND by server/src/auth/ownerAssertion.test.ts. The `entry` function above
// is a hand-written mirror of the server's signer, so it could drift silently; these rows
// cannot. If the engine ever stops accepting an entry the server would mint, every login on a
// world with an owner secret configured breaks, and this is the test that says so first.
interface Vector {
    secret: string;
    uid: string;
    character: string;
    exp: number;
    entry: string;
}

const vectors: Vector[] = (JSON.parse(fs.readFileSync(new URL('./ownerAssertion.vectors.json', import.meta.url), 'utf8')) as { vectors: Vector[] }).vectors;

test('every shared vector minted by the front server is accepted here', () => {
    assert.ok(vectors.length >= 5, 'the vector file must carry the rows both suites were written against');
    for (const v of vectors) {
        assert.deepEqual(
            verifyOwnerHeader(v.entry, v.character, v.secret, v.exp - 1000),
            { uid: v.uid, character: v.character, exp: v.exp },
            `vector ${v.uid}/${v.character} did not verify: the two HMAC implementations have drifted`
        );
        // The same row proves the local mirror agrees with the server's output byte for byte.
        assert.equal(entry(v.uid, v.character, v.exp, v.secret), v.entry);
    }
});

test('a shared vector is refused under a different secret, name or clock', () => {
    for (const v of vectors) {
        assert.equal(verifyOwnerHeader(v.entry, v.character, `${v.secret}!`, v.exp - 1000), null);
        assert.equal(verifyOwnerHeader(v.entry, 'mallory', v.secret, v.exp - 1000), null);
        assert.equal(verifyOwnerHeader(v.entry, v.character, v.secret, v.exp), null);
    }
});
