/**
 * The pack-ID guard behind `tools/pack/BuildOverlay.ts`. It lives here rather than beside the
 * tool because the engine suite is run as `npx tsx --test src/idlescape/*.test.ts`, and a guard
 * nobody runs is not a guard.
 */
import { test, after, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { changedPacks, hashPacks } from '#tools/pack/packGuard.js';

let dir = '';
const made: string[] = [];

beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), 'idlescape-packs-'));
    made.push(dir);
});

after(() => {
    for (const scratch of made) {
        fs.rmSync(scratch, { recursive: true, force: true });
    }
});

test('changedPacks names a removed and a rewritten pack in name order, and lets a generated one through', () => {
    const before = new Map([
        ['varp.pack', 'aaa'],
        ['obj.pack', 'bbb'],
        ['inv.pack', 'ccc']
    ]);
    const after = new Map([
        ['varp.pack', 'aaa'], // untouched
        ['obj.pack', 'BBB'], // rewritten: the id renumbering this guard exists for
        ['category.pack', 'ddd'] // generated by this run: absent from a fresh clone, holds no stored id
        // inv.pack removed
    ]);

    assert.deepEqual(changedPacks(before, after), ['inv.pack', 'obj.pack']);
});

test('a fresh clone that gains only generated packs trips nothing, and a renumber beside them still does', () => {
    const fresh = new Map([['obj.pack', 'bbb'], ['npc.pack', 'nnn']]);
    const packed = new Map([...fresh, ['category.pack', 'c'], ['dbrow.pack', 'd'], ['script.pack', 's']]);
    assert.deepEqual(changedPacks(fresh, packed), []);
    const renumbered = new Map([...packed, ['obj.pack', 'BBB']]);
    assert.deepEqual(changedPacks(fresh, renumbered), ['obj.pack']);
});

test('changedPacks reports nothing when the two hashings agree, including two empty ones', () => {
    const hashes = new Map([['varp.pack', 'aaa']]);
    assert.deepEqual(changedPacks(hashes, new Map(hashes)), []);
    assert.deepEqual(changedPacks(new Map(), new Map()), []);
});

test('hashPacks hashes only .pack files, and a rewrite trips changedPacks end to end', () => {
    fs.writeFileSync(path.join(dir, 'varp.pack'), '359=banktab_size_1\n');
    fs.writeFileSync(path.join(dir, 'obj.pack'), '0=coins\n');
    fs.writeFileSync(path.join(dir, 'interface.order'), 'not a pack file\n');

    const before = hashPacks(dir);
    assert.deepEqual([...before.keys()].sort(), ['obj.pack', 'varp.pack'], 'interface.order carries no ids');
    assert.deepEqual(changedPacks(before, hashPacks(dir)), [], 'hashing the same bytes twice is stable');

    // what a build.verify=false run does when a config name has no ID line
    fs.appendFileSync(path.join(dir, 'varp.pack'), '368=banktab_size_10\n');
    fs.writeFileSync(path.join(dir, 'interface.order'), 'edited, and still ignored\n');

    assert.deepEqual(changedPacks(before, hashPacks(dir)), ['varp.pack']);
});

test('a missing pack directory hashes to empty rather than throwing', () => {
    const missing = path.join(dir, 'no-such-dir');
    assert.deepEqual([...hashPacks(missing).keys()], []);
    assert.deepEqual(changedPacks(hashPacks(missing), hashPacks(missing)), []);
});
