import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import {
  OWNER_ASSERTION_MAX_ENTRIES, OWNER_ASSERTION_TTL_MS, OWNER_COOKIE,
  buildOwnerCookie, ownerCookieHeader, signOwnerAssertion, splitOwnerCookie, verifyOwnerAssertion
} from './ownerAssertion';

const SECRET = 'x'.repeat(32);
const NOW = 1_800_000_000_000;

describe('owner assertion', () => {
  test('round-trips uid, character and expiry', () => {
    const entry = signOwnerAssertion(SECRET, { uid: 'uid123', character: 'bob', exp: NOW + 1000 });
    expect(entry.split('.')).toHaveLength(4);
    expect(verifyOwnerAssertion(SECRET, entry, NOW)).toEqual({ uid: 'uid123', character: 'bob', exp: NOW + 1000 });
  });

  test('rejects a tampered character, a tampered uid, a wrong secret and an expired entry', () => {
    const entry = signOwnerAssertion(SECRET, { uid: 'uid123', character: 'bob', exp: NOW + 1000 });
    const [uid, , exp, sig] = entry.split('.');
    expect(verifyOwnerAssertion(SECRET, `${uid}.eve.${exp}.${sig}`, NOW)).toBeNull();
    expect(verifyOwnerAssertion(SECRET, `evil.bob.${exp}.${sig}`, NOW)).toBeNull();
    expect(verifyOwnerAssertion('y'.repeat(32), entry, NOW)).toBeNull();
    expect(verifyOwnerAssertion(SECRET, entry, NOW + 2000)).toBeNull();
  });

  test('rejects malformed entries without throwing', () => {
    for (const bad of ['', 'a', 'a.b', 'a.b.c', 'a.b.notanumber.sig', 'a.b.1.']) {
      expect(verifyOwnerAssertion(SECRET, bad, NOW)).toBeNull();
    }
  });

  test('an empty secret refuses to sign (buildOwnerCookie must never emit an unverifiable entry)', () => {
    expect(() => signOwnerAssertion('', { uid: 'uid123', character: 'bob', exp: NOW + 1000 })).toThrow();
  });

  test('an empty secret never verifies (a misconfigured server must not authorise anyone)', () => {
    const entry = signOwnerAssertion(SECRET, { uid: 'uid123', character: 'bob', exp: NOW + 1000 });
    expect(verifyOwnerAssertion('', entry, NOW)).toBeNull();
  });

  test('the cookie accumulates characters, replaces the same one, drops expired and caps the list', () => {
    let cookie = buildOwnerCookie(SECRET, null, { uid: 'u', character: 'one', exp: NOW + OWNER_ASSERTION_TTL_MS }, NOW);
    cookie = buildOwnerCookie(SECRET, cookie, { uid: 'u', character: 'two', exp: NOW + OWNER_ASSERTION_TTL_MS }, NOW);
    expect(splitOwnerCookie(cookie)).toHaveLength(2);

    // re-minting a session for 'one' replaces its entry rather than appending a second
    cookie = buildOwnerCookie(SECRET, cookie, { uid: 'u', character: 'one', exp: NOW + OWNER_ASSERTION_TTL_MS }, NOW);
    expect(splitOwnerCookie(cookie)).toHaveLength(2);
    expect(splitOwnerCookie(cookie).map(e => verifyOwnerAssertion(SECRET, e, NOW)?.character)).toEqual(['two', 'one']);

    // a stale entry from an expired session is dropped on the next mint
    const stale = signOwnerAssertion(SECRET, { uid: 'u', character: 'old', exp: NOW - 1 });
    cookie = buildOwnerCookie(SECRET, `${stale}~${cookie}`, { uid: 'u', character: 'three', exp: NOW + OWNER_ASSERTION_TTL_MS }, NOW);
    expect(splitOwnerCookie(cookie).map(e => verifyOwnerAssertion(SECRET, e, NOW)?.character)).toEqual(['two', 'one', 'three']);

    for (const name of ['four', 'five', 'six']) {
      cookie = buildOwnerCookie(SECRET, cookie, { uid: 'u', character: name, exp: NOW + OWNER_ASSERTION_TTL_MS }, NOW);
    }
    const names = splitOwnerCookie(cookie).map(e => verifyOwnerAssertion(SECRET, e, NOW)?.character);
    expect(names).toHaveLength(OWNER_ASSERTION_MAX_ENTRIES);
    expect(names).toEqual(['one', 'three', 'four', 'five', 'six']);   // oldest ('two') evicted
  });

  test('another account signing in replaces the cookie instead of merging', () => {
    const mine = buildOwnerCookie(SECRET, null, { uid: 'u1', character: 'one', exp: NOW + 1000 }, NOW);
    const theirs = buildOwnerCookie(SECRET, mine, { uid: 'u2', character: 'two', exp: NOW + 1000 }, NOW);
    expect(splitOwnerCookie(theirs)).toHaveLength(1);
    expect(verifyOwnerAssertion(SECRET, splitOwnerCookie(theirs)[0], NOW)?.uid).toBe('u2');
  });

  test('the Set-Cookie header is HttpOnly, Lax, path-wide and Secure only on https', () => {
    const header = ownerCookieHeader('v', false);
    expect(header.startsWith(`${OWNER_COOKIE}=v; Path=/; Max-Age=${OWNER_ASSERTION_TTL_MS / 1000}; HttpOnly; SameSite=Lax`)).toBe(true);
    expect(header).not.toContain('Secure');
    expect(ownerCookieHeader('v', true)).toContain('; Secure');
  });
});

// --- The shared vector file (the drift alarm) --------------------------------
// engine-custom/src/idlescape/ownerAssertion.vectors.json was generated by signOwnerAssertion
// below and is read by BOTH this suite and the engine overlay's own ownerAssertion.test.ts.
// The engine holds a separate implementation of the same HMAC (it cannot import from here: it
// is a different package, and the overlay is copied into a pinned upstream clone), so nothing
// but a shared fixture can prove the two still agree. A change to the wire format that is made
// on one side only fails here, at unit-test speed, instead of at the next login.
interface Vector { secret: string; uid: string; character: string; exp: number; entry: string }

const vectors: Vector[] = (JSON.parse(
  readFileSync(new URL('../../../engine-custom/src/idlescape/ownerAssertion.vectors.json', import.meta.url), 'utf8')
) as { vectors: Vector[] }).vectors;

describe('shared owner assertion vectors', () => {
  test('this signer still produces every recorded entry byte for byte', () => {
    expect(vectors.length).toBeGreaterThanOrEqual(5);
    for (const v of vectors) {
      expect(signOwnerAssertion(v.secret, { uid: v.uid, character: v.character, exp: v.exp })).toBe(v.entry);
    }
  });

  test('this verifier accepts every recorded entry, and refuses it once expired', () => {
    for (const v of vectors) {
      expect(verifyOwnerAssertion(v.secret, v.entry, v.exp - 1000)).toEqual({ uid: v.uid, character: v.character, exp: v.exp });
      expect(verifyOwnerAssertion(v.secret, v.entry, v.exp)).toBeNull();
    }
  });
});
